RetroDataModelArguments:
  # DataArguments
  max_seq_length: 512
  max_answer_length: 30
  doc_stride: 128
  return_token_type_ids: True
  pad_to_max_length: True
  preprocessing_num_workers: 5
  overwrite_cache: False
  version_2_with_negative: True
  null_score_diff_threshold: 0.0
  rear_threshold: 0.0
  n_best_size: 20
  use_choice_logits: False
  start_n_top: -1
  end_n_top: -1
  beta1: 1
  beta2: 1
  best_cof: 1

  # SketchModelArguments - Freeze Sketch module
  sketch_model_name: deepset/roberta-base-squad2
  sketch_architectures: RobertaForSequenceClassification

  # IntensiveModelArguments - Chỉ train Intensive module
  intensive_model_name: deepset/roberta-base-squad2
  intensive_model_mode: finetune # Train intensive
  intensive_architectures: RobertaForQuestionAnsweringAVPool

TrainingArguments:
  run_name: baseline-intensive-only

  output_dir: outputs/baseline_intensive_only
  overwrite_output_dir: True

  learning_rate: 2e-5
  per_device_train_batch_size: 12
  per_device_eval_batch_size: 12
  num_train_epochs: 5.0

  save_strategy: steps
  save_steps: 1000
  save_total_limit: 2

  load_best_model_at_end: True
  evaluation_strategy: epoch
  metric_for_best_model: eval_f1

  no_cuda: True
  fp16: False
  warmup_ratio: 0.1
  weight_decay: 0.01

  logging_dir: outputs/baseline_intensive_only/logs
  logging_steps: 100
