RetroDataModelArguments:

    # DataArguments
    max_seq_length: 512
    max_answer_length: 30
    doc_stride: 128
    return_token_type_ids: True
    pad_to_max_length: True
    preprocessing_num_workers: 5
    overwrite_cache: False
    version_2_with_negative: True
    null_score_diff_threshold: 0.0
    rear_threshold: 0.0
    n_best_size: 20
    use_choice_logits: False
    start_n_top: -1
    end_n_top: -1
    beta1: 1
    beta2: 1
    best_cof: 1

    # SketchModelArguments
    sketch_model_name: deepset/roberta-base-squad2
    sketch_architectures: RobertaForSequenceClassification

    # IntensiveModelArguments
    intensive_model_name: deepset/roberta-base-squad2
    intensive_model_mode: finetune
    intensive_architectures: RobertaForQuestionAnsweringAVPool


TrainingArguments:
    run_name: squadv2-roberta-base-sketch

    output_dir: /kaggle/working/outputs
    overwrite_output_dir: False

    learning_rate: 2e-5
    per_device_train_batch_size: 12
    per_device_eval_batch_size: 12
    num_train_epochs: 5.0         # Phase 1: 5 epochs
    # num_train_epochs: 10.0         # Phase 2: 10 epochs


    save_strategy: steps
    save_steps: 1000
    save_total_limit: 2           # Save only the last 2 checkpoints

    load_best_model_at_end: False
    evaluation_strategy: epoch

    no_cuda: False
    fp16: True
    warmup_ratio: 0.1
    weight_decay: 0.01

    logging_dir: /kaggle/working/logs
    logging_steps: 100
